name: Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: 'v2.54.1'

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-13"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # install pip packages
      - name: Install pyrealsense2-mac
        run: pip install pyrealsense2-mac

      # run test
      - name: Test pyrealsense2-mac
        run: |
          cd $GITHUB_WORKSPACE
          python test/count-devices.py
